version: '3'
name: python-junior-task
services:
  postgre:
    image: postgres:latest
    container_name: postgres_junior_task
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    command: sh /service/docker/startup.sh
    ports:
      - 7777:8000
    depends_on:
      postgre:
        condition: service_healthy